# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Karen Kuang
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
domain: karenSashimi.github.io
baseurl: "" # the subpath of the site
url: "https://karenSashimi.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Projects
    - name: Experiences
    # - name: Blog

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: karenkuang1111@gmail.com
      link: mailto:karenkuang1111@gmail.com
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/karen-yx-kuang
    # - name: GitHub
    #   link: http://github.com/zichuan-scott-xu

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
sass:
  style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
